---
- hosts: all
  become: yes
  tasks:
      - name: Create user
        user:
          name: motsebo
          comment: Franck motsebo
          group: root
      - name: Create file
        file:
          path: /opt/config
          state: touch
          mode: '0600'
      - name: Create a directory
        file:
          path: /etc/some_directory
          state: directory
          mode: '0755'
      - name: create group
        group:
          name: managers
          state: present
      - name: install Apache
        yum:
          name: httpd
          state: latest
      - name: start apache
        service:
          name: httpd
          state: started
          enabled: yes
      - name: download package
        get_url:
          url: https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz
          dest: /opt
          mode: 0644
      - name: install pakages
        yum:
          name: "{{item}}"
          state: present
        loop:
          - git
          - wget
          - httpd        
